# Generated by Django 4.0.2 on 2022-02-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0003_rename_title_book_name_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
